# Generated by Django 3.2.12 on 2022-03-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_image_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_model',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
