# Generated by Django 3.2.12 on 2022-03-15 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_image_model_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100, null=True)),
                ('town', models.CharField(max_length=150, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='image_Model',
        ),
    ]
