# Generated by Django 3.2.12 on 2022-03-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220316_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_details',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
