# Generated by Django 4.2 on 2023-04-13 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_seller"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appuser",
            options={"verbose_name": "App User", "verbose_name_plural": "App Users"},
        ),
        migrations.AlterModelOptions(
            name="seller",
            options={"verbose_name_plural": "Sellers"},
        ),
    ]
