# Generated by Django 4.2 on 2023-04-27 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_sellerrating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerdetails",
            name="sellerId",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_detail",
                to="users.seller",
            ),
        ),
    ]
