# Generated by Django 4.2 on 2023-04-17 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subcategory",
            old_name="catogoryId",
            new_name="categoryId",
        ),
    ]
