# Generated by Django 4.2 on 2023-04-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_brand_image_product_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
