# Generated by Django 4.2 on 2023-05-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_userwishlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimages",
            name="variant_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="UserWishListItem",
        ),
    ]
