# Generated by Django 3.2.12 on 2022-03-08 08:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_model',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to=''),
        ),
    ]
