# Generated by Django 3.2.12 on 2022-04-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seller_details_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_details',
            name='delivering',
            field=models.BooleanField(default=False),
        ),
    ]
